<template>
    <div id="app" class="container">
        <heading 
            :name="heading.name"
            :subheaders="heading.subheaders">
        </heading>

        <projects 
            :projects="projects">
        </projects>

        <work-experience
            :experiences="workExperiences">
        </work-experience>

        <volunteer-experience></volunteer-experience>
        <education></education>
        <skills></skills>
        <logo></logo>
    </div>
</template>

<script>
import Heading from './components/Heading';
import Projects from './components/Projects';
import WorkExperience from './components/WorkExperience';
import VolunteerExperience from './components/VolunteerExperience';
import Education from './components/Education';
import Skills from './components/Skills';
import Logo from './components/Logo';

export default {
    data() {
        return {
            heading: {
                name: 'Senhung Wong',
                subheaders: [
                    {
                        text: 'wongsenw@sfu.ca', 
                        icon: 'far fa-envelope', 
                        link: 'mailto:wongsenw@sfu.ca', 
                        newpage: false
                    },
                    {
                        text: 'senhung.net', 
                        icon: 'fas fa-external-link-alt', 
                        link: 'http://senhung.net', 
                        newpage: true
                    },
                    {
                        text: 'github.com/senhungwong', 
                        icon: 'fab fa-github', 
                        link: 'https://github.com/senhungwong', 
                        newpage: true
                    },
                ]
            },
            projects: [
                {
                    name: 'Resume Generator', 
                    link: 'https://github.com/senhungwong/resume-generator',
                    description: 'Generates a static web resume written on Vue (a front-end JavaScript framework). This resume is generated by this tool.',
                    demo: 'http://resume.senhung.net/'
                },
                {
                    name: 'GPA Calculator', 
                    link: 'https://github.com/senhungwong/gpa-calculator-desktop',
                    description: 'A cross-platform desktop application using electron framework that calculates GPA in both 4.00 and 4.33 scales.',
                    demo: null
                },
            ],
            workExperiences: [
                {
                    company: 'Blockchain Intelligence Group',
                    link: 'https://blockchaingroup.io/',
                    location: 'Vancouver, BC',
                    title: 'Back-end Developer',
                    from: '2018-01-01',
                    to: '2018-08-31',
                },
            ],
        }
    },
    components: {
        Heading,
        Projects,
        WorkExperience,
        VolunteerExperience,
        Education,
        Skills,
        Logo
    }
}
</script>

<style>
@import './themes/green-resume.css';
</style>
